{
  des: 'Add',
    method: 'POST',
      url: 'http://localhost:1001/Config',
        requestHeader: {
    'content-type': 'application/json'
  },
  requestBody: {
    _id: Uuid,
      project_id: Uuid,
        account_id: Uuid,
          name: string,
            config: object,
              created_at ?: Date,
              updated_at ?: Date
  }
}

{
  des: 'Get list',
    method: 'GET',
      url: 'http://localhost:1001/Config'
}

{
  des: 'Update',
    method: 'PUT',
      url: 'http://localhost:1001/Config/ITEM_ID',
        requestHeader: {
    'content-type': 'application/json'
  },
  requestBody: {
    _id: Uuid,
      project_id: Uuid,
        account_id: Uuid,
          name: string,
            config: object,
              created_at ?: Date,
              updated_at ?: Date
  }
}

{
  des: 'Get detail',
    method: 'GET',
      url: 'http://localhost:1001/Config/ITEM_ID'
}

{
  des: 'Delete',
    method: 'DELETE',
      url: 'http://localhost:1001/Config/ITEM_ID'
}