{
  des: 'Add log',
  method: 'POST',
  url: 'http://localhost:1004/Log',
  requestHeader: {
    'content-type': 'application/json',
    token: '59566907ad1fd629540c4b3d59566927ad1fd629540c4b42595a022b9c1147109c9394b6?2700'
  },
  requestBody: {
    type: 0,
    title: 'Error something',
    status:  1,
    customize: 'thanh',
    event_type: 'active_account',
    error: 'got something error'
  }
}

{
  des: 'Update',
  method: 'PUT',
  url: 'http://localhost:1004/Log/595a03396a7f9504609c11ae',
  requestHeader: {
    'content-type': 'application/json',
    token: '59566907ad1fd629540c4b3d59566927ad1fd629540c4b42595a022b9c1147109c9394b6?2700'
  },
  requestBody: {
    status: 0
  }
}

{
  des: 'Get list',
    method: 'GET',
      url: 'http://localhost:1001/Log'
}

{
  des: 'Update',
    method: 'PUT',
      url: 'http://localhost:1001/Log/ITEM_ID',
        requestHeader: {
    'content-type': 'application/json'
  },
  requestBody: {
    _id: Uuid,
      project_id: Uuid,
        account_id: Uuid,
          type: number,
            title: string,
              created_at ?: Date
  }
}

{
  des: 'Get detail',
    method: 'GET',
      url: 'http://localhost:1001/Log/ITEM_ID'
}

{
  des: 'Delete',
  method: 'DELETE',
  url: 'http://localhost:1001/Log/ITEM_ID'
}