{
  des: 'Add',
  method: 'POST',
  url: 'http://localhost:1003/Mail/Send/5972a7e2a540351f88c3c2eb',
  requestHeader: {
    'content-type': 'application/json',
    token: '4b8f28ebae90c98ff00fa2f92092201f?2700'
  },
  requestBody: {
    subject: 'Test 123',
    html: '<a href="#">Text</a>',
    from: 'clipvnet@gmail.com',
    to: ['thanhdt@viosoft.com'],
    cc: ['doanthuanthanh88@gmail.com']
  }
}

{
  des: 'Get list',
    method: 'GET',
      url: 'http://localhost:1001/Mail'
}

{
  des: 'Update',
    method: 'PUT',
      url: 'http://localhost:1001/Mail/ITEM_ID',
        requestHeader: {
    'content-type': 'application/json'
  },
  requestBody: {
    _id: Uuid,
      config_id: Uuid,
        project_id: Uuid,
          account_id: Uuid,
            subject: string,
              text: string,
                html: string,
                  from: string,
                    to: Array,
                      cc: Array,
                        created_at ?: Date,
                        updated_at ?: Date
  }
}

{
  des: 'Get detail',
    method: 'GET',
      url: 'http://localhost:1001/Mail/ITEM_ID'
}

{
  des: 'Delete',
    method: 'DELETE',
      url: 'http://localhost:1001/Mail/ITEM_ID'
}